# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 20:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    replaces = [('users', '0001_initial'), ('users', '0002_user_password_plain'), ('users', '0003_physicalmachine'), ('users', '0004_auto_20170430_1917'), ('users', '0005_userlog_virtualmachines'), ('users', '0006_auto_20170430_2030'), ('users', '0007_auto_20170501_1444'), ('users', '0008_auto_20170501_1603'), ('users', '0009_auto_20170510_1654'), ('users', '0010_auto_20170510_1732'), ('users', '0011_auto_20170510_1745'), ('users', '0012_auto_20170514_1941'), ('users', '0013_auto_20170514_2000')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('credit', models.IntegerField(default=0)),
                ('password_plain', models.CharField(default=datetime.datetime(2017, 4, 30, 17, 41, 48, 423333, tzinfo=utc), max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('mem', models.IntegerField(default=0)),
                ('mem_gpu', models.IntegerField(default=0)),
                ('gpu_name', models.CharField(max_length=200)),
                ('cpu_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('disk_size', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('description', models.TextField(max_length=1000)),
                ('shot_description', models.CharField(max_length=200)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
                ('physical_machine_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.PhysicalMachine')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualMachines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('creation_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('gpu_mem', models.IntegerField(default=0)),
                ('mem', models.IntegerField(default=0)),
                ('disk_size', models.IntegerField(default=0)),
                ('connection_info', models.CharField(max_length=200)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
                ('physical_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.PhysicalMachine')),
                ('cpu_cores', models.IntegerField(default=2)),
            ],
        ),
        migrations.AddField(
            model_name='physicalmachine',
            name='cpu_cores',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_plain',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_plain',
            field=models.CharField(max_length=20),
        ),
    ]
