# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 17:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_plain',
            field=models.CharField(default=datetime.datetime(2017, 4, 30, 17, 41, 48, 423333, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
    ]
