# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170514_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachines',
            name='connection_host',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='virtualmachines',
            name='connection_password',
            field=models.CharField(default='root', max_length=20),
        ),
        migrations.AddField(
            model_name='virtualmachines',
            name='connection_port',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='virtualmachines',
            name='cost_money_per_day',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='virtualmachines',
            name='connection_info',
            field=models.CharField(default='', max_length=200),
        ),
    ]
