# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_password_plain'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mem', models.IntegerField(default=0)),
                ('mem_gpu', models.IntegerField(default=0)),
                ('gpu_name', models.CharField(max_length=200)),
                ('cpu_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('disk_size', models.IntegerField(default=0)),
            ],
        ),
    ]
