# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170604_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlog',
            name='physical_machine_name',
        ),
    ]
