# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_physicalmachine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalmachine',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
