# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userlog_physical_machine_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlog',
            old_name='shot_description',
            new_name='short_description',
        ),
    ]
