# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 19:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170430_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('description', models.CharField(max_length=1000)),
                ('shot_description', models.CharField(max_length=200)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
                ('physical_machine_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.PhysicalMachine')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualMachines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('creation_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('gpu_mem', models.IntegerField(default=0)),
                ('mem', models.IntegerField(default=0)),
                ('disk_size', models.IntegerField(default=0)),
                ('expiration_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('connection_info', models.CharField(max_length=200, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
                ('physical_machine_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.PhysicalMachine')),
            ],
        ),
    ]
