# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170607_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_free_user',
            field=models.BooleanField(default=True),
        ),
    ]
