# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userlog_virtualmachines'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalmachine',
            name='cpu_cores',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='virtualmachines',
            name='cpu_cores',
            field=models.IntegerField(default=2),
        ),
    ]
