# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_is_free_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachines',
            name='hdd_disk_size',
            field=models.IntegerField(default=0),
        ),
    ]
