# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170430_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='virtualmachines',
            old_name='physical_machine_name',
            new_name='physical_machine',
        ),
        migrations.RemoveField(
            model_name='virtualmachines',
            name='expiration_time',
        ),
    ]
