# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20170501_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachines',
            name='connection_info',
            field=models.CharField(max_length=200),
        ),
    ]
