# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20170501_1603'),
    ]

    operations = [
    ]
