# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20170510_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
