# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20170510_1732'),
    ]

    operations = [
    ]
