# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20170510_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_plain',
            field=models.CharField(default='', max_length=20),
        ),
    ]
