# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20170514_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_plain',
            field=models.CharField(max_length=20),
        ),
    ]
